### PR TITLE
Run2 photons

### LINKED ISSUE #37: We should reintegrate the ICAnalysis-PhotonHadTowerOverEmCalculator back into the photon producer
This package didn't compile in an old CMSSW version. It should now and should be reintegrated into ICPhotonProducer

### PR DESCRIPTION
**Pull request by pjdunne**
Adding a working photon recipe to higgsinv run 2 config, and making the necessary changes to Photon and ICPhotonProducer. Resolve #37  by reintegrating HoverE calculator and addint a module to take electron conversion veto from PAT.

### CODE REVIEW

**Comment by pjdunne** [comment]
please test

**Comment by pjdunne** [comment]
please test

**Comment by pjdunne** [comment]
please test

**Comment by pjdunne** [comment]
please test

**Comment by ajgilbert** [comment]
Sorry I wasn't following developments very closely yesterday but I think there are a few issues with this PR:
- pu and chargedAll isolation sums were intentionally not included before because my understanding was the Egamma pog do not recommend using them - i see these are only available in pat anyway. Unless these are definitely needed there's no reason to include them
- Same concern for the DR=0.4 isolation, I don't think it's recommended but maybe i missed something
- In any case, I think reading a second collection, `pat_photons_handle` and trying to pick up values from here is risky: there's no guarantee the two collections are aligned or even have the same size, and there are no checks for this in the code. My intention was you just read the values directly via the `photons_handle` edm::View which could point to either a reco::Photon or pat::Photon collection.

**Comment by pjdunne** [comment]
Hi, the pu and chargedAll isolation sums aren't currently used, but they are produced by the standard pf photon isolation cff, so I thought we should include them in case they become used later.

For the DR=0.4 isolation 0.3 is indeed recommended as it is for electrons and muons, but as we have both for electrons and muons I thought it would be useful to have the ability to store both for photons.

The pat_photons_handle_ is the same collection (they both come from input_) so it will have the same size, but we only get it from the event in the case that the isolation from pat flag is true, this way if the input collection is just a reco::photon and not a pat::photon there won't be a problem. The get functions for the isolation do not work on the edm::Handle<edm::View<reco::Photon> >.

**Comment by ajgilbert** [comment]
Ah right ok I didn't notice that input_ was the same. So the pu and chargedAll isolation are only calculated in the pat sequence? But in the case do_iso_from_pat_ is true then you write the same values into the _03 and _04 collections?

**Comment by pjdunne** [comment]
pu and chargedAll isolation are calculated in here "CommonTools.ParticleFlow.Isolation.pfPhotonIsolation_cff", which is the corresponding cff to the ones used to calculate the electron and muon isolations.

If do_iso_from_pat is true then yes I guess if you asked it to store both the 0.3 and 0.4 isolation it would put the same in both, I could put a check in that it'll only let you ask for one to be filled if do_iso_from_pat_ is true.

**Comment by pjdunne** [comment]
I've just committed the check on filling the 0.3 and 0.4 isolation both from the pat isolation in the run2_photons branch, but I'll have to make a new pull request to merge it in. Are there any other changes that you think it needs?

**Pull request merged**
