### PR TITLE
Warnings as errors

### PR DESCRIPTION
**Pull request by ajgilbert**
been meaning to set this for a while. of course it's annoying to have to fix things more often when developing but it can catch mistakes that would otherwise be missed. but if people are against this we can drop it.

### CODE REVIEW

**Comment by rcl11** [comment]
I'm fine with this personally. @adewit I'll take care of the couple of compiler warnings in HiggsTauTau directory as part of my next pull request.

**Comment by pjdunne** [comment]
Me too as long as we fix all the problems currently present before merging this pull request.

**Comment by ajgilbert** [comment]
please test

**Comment by ajgilbert** [comment]
will get the lists of things to fix when the tests come back. it's possible that different warnings will appear with different versions of the compiler. no rush though, we can leave this open for a while

**Comment by adewit** [comment]
All warnings in HiggsTauTau and related directories fixed, @pjdunne can you take care of those in HiggsNuNu?

**Comment by ajgilbert** [comment]
Hi all, the test machine is down temporarily - back soon

**Comment by ajgilbert** [comment]
please test clean

**Comment by adewit** [comment]
please test

**Pull request merged**
