### PR TITLE
Tidying up HiggsTauTau directory ready for new code

### PR DESCRIPTION
**Pull request by rcl11**
Not much done so far but just so @ajgilbert and @adewit can see what I am working towards - I removed all code for 2012 eras which aren't data_2012_rereco and 2012 strategies which aren't paper2013 (2011 era and strategy is still kept for now although I doubt we will ever need it again). This mostly tidies up HiggsTauTau.cpp and especially HTTWeights. For now I just added as a placeholder a new era data_2015 which so far just has the kinematic cuts defined in HiggsTauTau.cpp following those on Riccardo's twiki - I plan to build on this as well as adding an appropriate new strategy name as more of the new objects are ready. In the spirit of keeping pull requests short and regular then maybe you can both check that you have no objections to what I've done so far and then I'll proceed with building up the stuff for the new objects via further pull requests.

### CODE REVIEW

**Comment by adewit** [comment]
No objections from my side. Can HTTConfig.h be cleaned up by removing the old eras and strategies from there too or are they still necessary for anything?

**Comment by ajgilbert** [comment]
All looks fine to me. I think we can leave data_2011 in for now just in case we wanted to recreate the 7TeV datacards, though I agree this is looking increasingly unlikely

**Comment by rcl11** [comment]
The only reason to not clean up HTTConfig is that there is one old script of Andrew's in HiggsTauTau/test which I currently haven't touched and still uses the old eras - it is TauIDMeasurement.cpp which is an old script from Moriond time which hence uses the Moriond eras. Basically I started to look into updating this script to the Paper era but then since I didn't know every detail of what this script does I concluded it was easier to simply leave the eras defined in HTTConfig. But I checked and it is definitely just this script - so we could do something about this if you think it's better/neater.

**Comment by ajgilbert** [comment]
you can delete TauIDMeasurement.cpp - there's nothing useful in there

**Comment by rcl11** [comment]
please test

**Comment by rcl11** [comment]
please test

**Pull request merged**
