### PR TITLE
W+jets mc study

### PR DESCRIPTION
**Pull request by ajgilbert**
Changes include:

 - Small fix to ICEventProducer to handle the special `consumes` call needed for the LHERunInfoProduct
 - cmsRun and crab cfg for producing sample with LHE event weights (otherwise just of copy of the most recent Fall15 cfgs)
 - Puts the `keep_if` and `copy_keep_if` functions in FnPredicates.h - slightly more convenient way of applying cuts than `erase_if` because you don't have to remember to reverse the logic somewhere
 - WJetsStudy analysis program and module added in HiggsTauTau area
 - Added python `uncertainties` package and TTree `MultiDraw` function to be able to do something similar to HTTAnalysisTools in pyROOT

Shouldn't interact with any of the main analysis code, but not urgent if you prefer to avoid any disruption atm.

### CODE REVIEW

**Comment by ajgilbert** [comment]
please test

**Comment by adewit** [comment]
:tada: First PR in which a bit of python breaks backwards compatibility?! You win one point ;-)
Otherwise fine to merge

**Comment by ajgilbert** [comment]
Thanks :-)

First I'll have to figure out how to fix this... bit of a tricky one.

**Comment by ajgilbert** [comment]
please test

**Pull request merged**
