### PR TITLE
Run2 electrons

### PR DESCRIPTION
**Pull request by adewit**
Changes to electrons for run 2. To run all of these, you need to:
(in CMSSW_X_Y_Z/src):
- git cms-merge-topic HuguesBrun:trigElecIdInCommonIsoSelection720 (for the electron ID MVA)
- git clone https://github.com/ajgilbert/ICAnalysis-ElectronConversionCalculator.git ICAnalysis/ElectronConversionCalculator
And if you want to run the cut-based ID producers at ntuple production level:
- git cms-merge-topic ikrav:egm_id_phys14 (for the cut-based ID producers)

It is not strictly necessary to run the cut based ID producers when producing the ntuple as a function that should do the same thing has been added in FnPredicates.cc (only "Veto'" so far), but could be useful to run them when testing that this function is working properly.

miniaod_cfg_electron-example.py contains the config for producing electrons from miniaod and aod (might want to create pat::electrons from aod, not done in this example)

### CODE REVIEW

**Comment by adewit** [comment]
please test

**Comment by ajgilbert** [comment]
Hi Adinda,

few questions:

 - what are PF03HadIsolation and PF03HadIsolationVal for - do these actually get used anywhere?
 - In VetoElectronIDPhys14 we have to be a bit careful. In the past we have never included isolation cuts as part of the electron ID, preferring to use working points determined in the htt group. It's probably ok to leave it here for now, but I could see it being useful to have a way to apply the ID and isolation parts separately
 - The addition of full5x5_sigma_IetaIeta_ is fine, but i expect it will fail some of the 5_X_Y tests as it's a new variable (the slc5 test is currently reporting as passing when it actually fails sometimes - check the logs to be sure)
 - What is the motivation for ICElectronIDMVAProducerMiniAOD? Is there not a module that already exists for this? Or is there at least a recipe you could link to?
 - I don't think you meant to change this: `gsf_tk_nhits_(0), → gsf_tk_nhits_(0.),`

**Comment by adewit** [comment]
Hi Andrew,
- PF03HadIsolation and PF03HadIsolationVal aren't used anywhere yet, but as we will be using isolation cone sizes of 0.3 (instead of 0.4) I started putting these functions in.
- Unfortunately there doesn't seem to be a standard module that runs the MVA on miniAOD - an anlyser example is described here: https://twiki.cern.ch/twiki/bin/view/CMS/MultivariateElectronIdentificationRun2, but this producer is based on the implementation in cmgtools (https://github.com/CERN-PH-CMG/cmg-cmssw/blob/ce10fcb42424912adc0c670260dd34dedcd38c6e/PhysicsTools/Heppy/src/EGammaMvaEleEstimatorFWLite.cc)

**Comment by adewit** [comment]
please test

**Comment by adewit** [comment]
please test

**Comment by adewit** [comment]
please test

**Comment by adewit** [comment]
please test

**Pull request merged**
