### PR TITLE
CLASS_MEMBER macro: safer to leave scope as private

### LINKED ISSUE #1: CLASS_MEMBER dangling public
After using the CLASS_MEMBER compiler macro the class is left in the public state.

### PR DESCRIPTION
**Pull request by ajgilbert**
fixes #1 (finally)

### CODE REVIEW

**Comment by pjdunne** [comment]
Hi, this might cause problems in the case where the state was protected before the macro was called, as it could stop inheriting classes accessing the variables where they can now.

**Comment by ajgilbert** [comment]
i think all such problems will get picked up by the compiler and can be fixed? maybe it could cause subtle problems by hiding virtual functions but I don't think we'll have many cases of this

**Comment by ajgilbert** [comment]
please test

**Comment by ajgilbert** [comment]
please test

**Comment by ajgilbert** [comment]
since this has been here for ages, and I think it's fine, I'll merge tomorrow morning if there are no objections. Generally the safest way to use this macro is to always call it within `private:` scope, that way the macro leaves the same scope at the end.

**Comment by pjdunne** [comment]
Fine with me

**Pull request merged**
