### PR TITLE
Run2 analysis

### PR DESCRIPTION
**Pull request by adewit**
@rcl11  and @ajgilbert - of course this is far from finished, but there have been quite a lot of commits already, so turning this into a pull request before it gets completely out of hand. Any comments?

Main points:
- HTTSequence can now run the full paper2013 analysis selection (and the selections that have so far been chosen for the phys14 samples, except for the trigger filter)
- generate_job.sh no longer uses eval to run the program you pass to it as the combination of eval with a file that takes command line json patches doesn't work.
- Addition of a function specification for taus in oneCollCompositeProducer is needed for the fully hadronic pair selection. I don't think the compiler will actually make this specification an inline function, but this was needed to avoid compiler errors. The other option would be to move the function definition from the .h to the .cc, but I assumed there was a reason for all of the function definitions to be in the header file
- Added a first version of a function that reads json fragments from strings like job:channels:et.mt.tt, which isn't fully functional yet - it only works for values that should be strings, and not for arbitrary depths. 
- HTTSyncTemp is a temporary version of HTTSync for the phys 14 samples, should be combined into one (more flexible) HTTSync module.

### CODE REVIEW

**Comment by ajgilbert** [comment]
ok to merge for me, though a few comments:

 - I'd avoid customising OneCollCompositeProducer for Taus like this because it's very analysis specific. I think it would be easier to use the regular CompositeProducer to build all possible pairs. The pairs that just contain the same tau twice will be removed by the pair deltaR cut, so this isn't a problem. Then you will still have two CompositeCandidates for each tau pair (with just the ordering reversed), but this isn't a actually a problem, as what we call tau1 and tau2 should be resolved by the pair selection algorithm (to be implemented in HTTPairSelector). For example, see a sorting function here: https://github.com/ajgilbert/ICHiggsTauTau/blob/master/Analysis/HiggsTauTau/src/HTTPairStudy.cc#L538-L557, that can simply be used like: https://github.com/ajgilbert/ICHiggsTauTau/blob/master/Analysis/HiggsTauTau/src/HTTPairStudy.cc#L334
 - For creating the json fragments in the config script you might find it easier to use the json module that can dump a python dictionary into json format, e.g.:
~~~
  import json
  ch = "et"
  json.dumps({ "filelist" : "blah.dat", "channel" : ch })
  '{"channel": "et", "filelist": "blah.dat"}'
~~~
 - I see what you mean about the problem with generate_job.sh, I'll try to understand later why it doesn't work
 - In the future it might be nice to merge HTTSync and HTTCategories into a single flat-tree producing module. For sure if you look in HTTCategories.cc all the category definition and histogram filling code could be removed now.

**Comment by adewit** [comment]
Thanks for the comments!
I see your point about the OneCollCompositeProducer. It does only sort them that way if the sort_by_isolation flag is set to true (it's off by default), but an additional "problem" I hadn't thought about is that if something changed in the default version of OneCollCompositeProducer::Execute we'd have to remember to propagate it to the customisation. Will look into just using the normal CompositeProducer.

Regarding eval: eval eats the quotes in whatever's eval'ed. I just had another look and various people on the internet say this doesn't happen if you add a backslash in front of the quotes. That would make the syntax overly cumbersome though, because this already needs to be done to correctly pass the json fragment from htt.py to the job script (and then you'd have to escape the backslash too to get it in correctly, so what is now \" in htt.py would have to become \\\" I think). 
Anyway, I don't think we *need* eval here. (That said, the method that checks for presence of ./ at the start of the program execution command fed to generate_job.sh isn't pretty, and should probably be replaced by something better, I just haven't come up with anything yet)

**Comment by adewit** [comment]
please test

**Comment by adewit** [comment]
please test

**Pull request merged**
