### PR TITLE
adding new variables to IC muon for medium ID and making a medium ID fun...

### LINKED ISSUE #26: Update ICMuonProducer to ensure we store all the variables needed to run the Muon ID at ntuple level
In run I we implemented the muon ID by storing in the ntuples all the variables used and then having a function in FnPredicates which implemented the ID. This now needs to be updated to the run II ID.

### PR DESCRIPTION
**Pull request by pjdunne**
...ction in fnpredicates to resolve #26

### CODE REVIEW

**Comment by pjdunne** [comment]
please test

**Comment by pjdunne** [comment]
please test

**Comment by ajgilbert** [comment]
Looks good, just a couple of comments:

 - Can you add links to twiki pages / talks somewhere for the new ID function definition as a comment in the code
 - Need to increase the ClassDef number in Muon.hh because the data members have changed

**Comment by pjdunne** [comment]
please test

**Comment by pjdunne** [comment]
please test

**Pull request merged**
