### PR TITLE
Adding badGlobalMuonTagger to ICMuonProducer

### PR DESCRIPTION
**Pull request by riccardodimaria**
Hi all,
the only files I changed are:
- ICMuonProducer.hh
- ICMuonProducer.cc
- default_producers_cfi.py
in order to add the badGlobalMuonTagger to the muon producer.
Have i forgotten to change some files?

Please, let me know if this is what you had in mind.

### CODE REVIEW

**Comment by riccardodimaria** [comment]
please test

**Comment by ajgilbert** [comment]
Hi Riccardo - you've actually changed 1370 files according to github ;-)
Can you close this PR and make a new one that only contains the discussed changes?

**Comment by ajgilbert** [comment]
(as an aside I would recommend making a tarred and zipped archive file for filelists - saves space and reduces the amount of files git has to keep track of)

**Comment by riccardodimaria** [comment]
Yeah, but all the other changes are related to HiggsNuNu.

**Comment by ajgilbert** [comment]
Ok, it's hard to check that when there are so many files in the diff. We usually try to follow the philosophy of putting new developments - especially to any common code - on a separate branch, as described here: https://git-scm.com/book/en/v2/Git-Branching-Branching-Workflows. For code that only touches the HiggsNuNu area it's fine for me if you push this straight to master (after rebasing).

**Comment by riccardodimaria** [comment]
Ok, I'm gonna close this PR then. Thanks.

**Pull request closed without merging**
