### PR TITLE
Nov ntuple

### PR DESCRIPTION
**Pull request by danielwinterbottom**
This is the branch I used to produce the latest version of the ntuples, adding new HLT paths, MET corrections and electron ID. It also has changes to the electron class adding sc_seed_eta variable.

### CODE REVIEW

**Comment by ajgilbert** [comment]
Don't see any issues myself, but just wondering where the updated HLT paths are - don't see them in the diff.

**Comment by danielwinterbottom** [comment]
They're added here: https://github.com/ajgilbert/ICHiggsTauTau/blob/NovNtuple/test/higgstautau_cfg_80X_Nov16.py#L1984-L2104

**Comment by danielwinterbottom** [comment]
please test

**Comment by danielwinterbottom** [comment]
please test

**Pull request merged**
