### PR TITLE
Tau energy scale

### PR DESCRIPTION
**Pull request by danielwinterbottom**

### CODE REVIEW

**Comment by danielwinterbottom** [comment]
please test

**Comment by danielwinterbottom** [comment]
please test

**Comment by danielwinterbottom** [comment]
This PR has been open a while which is completely my fault for forgetting about it. Adinda requested a while ago that I add a comment to make it clearer how the tau ES shifts works - I have added this now so I will merge this PR if there are no other issues?

**Comment by adewit** [comment]
Yes fine with me :-)

**Comment by ajgilbert** [comment]
please test

**Comment by danielwinterbottom** [comment]
please test

**Pull request merged**
