### PR TITLE
CMSSW 7_6_X compilation

### PR DESCRIPTION
**Pull request by adewit**
This fixes the first two parts of #105, any comments @ajgilbert? (comments from anyone else also welcome, of course!) 

For the multi-threading, I can only assume this isn't enabled by default. The only "problem" I've had with it when testing the changes in this PR is when some modules in my config were called in an order that, according to the resulting error message, wouldn't have worked in the multi-threaded framework, but that was always fixable by reshuffling the process calls. 

We should also add a 7_6_X release to the validation script (can I do this myself or is there more to it than adding an extra block in config_slc6.json?), but not hugely urgent.

### CODE REVIEW

**Comment by adewit** [comment]
please test

**Comment by adewit** [comment]
please test

**Comment by ajgilbert** [comment]
looks good to me - thanks for taking care of this.

I don't completely understand why it's necessary to reorder modules when the multithreaded mode is off, but I also didn't look into how this works at all yet, so maybe it's expected that we have to make some changes.

For adding the validation the problem is the script that's running also has to be restarted. I'll try to set up a system so anyone can log in to the machine and do it.

**Comment by adewit** [comment]
Yeah sorry I wasn't very clear there, it's a warning rather than an error, and it isn't really a big deal. Basically you can occasionally get a message (which doesn't seem to impair running) like this:
```
Module run order problem found: 
A consumes B, B consumes C, C after A [path p]
 Running in the threaded framework would lead to indeterminate results.
 Please change order of modules in mentioned Path(s) to avoid inconsistent module ordering.
```
Which I interpreted as "you're not running in multithreaded mode yet but if you were to do so this probably wouldn't work", though I may be wrong. Actually in this particular case 'A' *doesn't actually* use 'B' at all* which is why this was never a problem before. It's probably just that before the path is executed, CMSSW now checks whether there are any such potential inconsistencies, whereas before it never did so would just crash at some point if the modules were in the wrong order. I don't actually know enough about multithreading to understand why simply crashing while running isn't an option, but that's a different point entirely.

*'A' produces a jet from the slimmedJets collection, 'B' is a pu jet ID producer. Slimmed jets already have pu ID embedded, but "homemade" pat::Jets do not, so the jet producer requires a pu ID input producer name, even if it isn't used for slimmedJets. In this case the warning arises because a module named 'B' does exist (for a different jet collection) - even just changing the name of 'B' is enough to solve it. It's a little silly, really!

**Comment by ajgilbert** [comment]
Right I see, so maybe in the multithreaded framework modules get run in an unpredictable order, so sometimes C would run first and the path would be ok, other times not. Anyway I agree for us it doesn't matter.

**Pull request merged**
