### PR TITLE
Adding ID functions for photon to FnPredicates

### PR DESCRIPTION
**Pull request by pjdunne**
Adding Tight, Medium and Loose WPs from Spring15 here: https://twiki.cern.ch/twiki/bin/view/CMS/CutBasedPhotonIdentificationRun2

Also added photon to objects.hh

### CODE REVIEW

**Comment by pjdunne** [comment]
please test

**Comment by pjdunne** [comment]
As this checks out ok I'll merge this tomorrow morning if no one raises any issues. There are no changes to existing functions in FnPredicates.

**Comment by adewit** [comment]
Hi Patrick,
Shouldn't the isolation cuts be made on EA corrected isolation?

**Comment by pjdunne** [comment]
Ah I hadn't realised that wasn't what was stored in the events. Yes it should I'll update it.

**Comment by pjdunne** [comment]
please test

**Comment by ajgilbert** [comment]
it's fine for me, but one thing to be careful with is which rho value is used. In the past I remember it wasn't the same rho as used for the fastjet area subtraction but rather one calculated in a reduced eta range. Can store a different "lepton_rho" in EventInfo if necessary

**Comment by pjdunne** [comment]
Thanks, the twiki says that we should use the same rho we've been using for fastjet "fixedGridRhoFastjetAll", but I'll keep an eye out for changes and add a separate one if necessary.

**Pull request merged**
