### PR TITLE
Run 2 datacards and svfit

### PR DESCRIPTION
**Pull request by adewit**
Unfortunately this one has become a little large, this basically contains:
- New SVFit as a subdirectory, and new SVFit interfacing code as it's a bit different from the legacy svfit code
- First version of simple datacard-making script, and name changes of the background components in emu to align them with those of the other channels

### CODE REVIEW

**Comment by adewit** [comment]
please test

**Comment by adewit** [comment]
please test

**Comment by adewit** [comment]
The new SVFit code was added as a subdirectory here (ie copying over all of the relevant files), but might be better to add it as a subtree in the interest of keeping track of updates to the code - @rcl11 and @ajgilbert do you agree?

**Comment by adewit** [comment]
Actually there are a couple of reasons not to add svfit as a subtree at the moment, will merge this soon and potentially make it a subtree with the next svfit iteration...

@pjdunne I think this commit contains only one change that will affect you (I've changed the eta>3 pfjetid to require number of neutral particles >10 instead of number of constituents > 10, as per the recommendation on the twiki)

**Comment by ajgilbert** [comment]
Hi, generally I'd be in favour of the subtree option. what's the issue with it at the moment?

**Comment by adewit** [comment]
I was hoping you wouldn't ask, am taking the path of least resistance here after all  ("I'd quite like to merge all of the rest of this PR in, to add svfit as a subtree I need to install a new version of git which knowing myself a little bit can easily cost a lot of time that I want to spend on other things right now"). I'll sort this out when I can sit down and do it

**Comment by pjdunne** [comment]
As long as the ID agrees with what's on the twiki I'm fine with the changes that affect me. Thanks

**Comment by ajgilbert** [comment]
right yes I vaguely remember the git version being a problem before when doing this - ok fine for me then

**Pull request merged**
