### PR TITLE
Mar05 production updates

### PR DESCRIPTION
**Pull request by adewit**
Adds new samples to plotting (incl high mass DY stitching weights) and recoil corrections (W and DY only)
In addition, submitting other sequences than the default (scale_X_up/down), can now run htt_fall15.py with eg --scales="default,scale_t", which will submit the jobs default, scale_t_up and scale_t_down.

### CODE REVIEW

**Comment by adewit** [comment]
please test

**Comment by ajgilbert** [comment]
please test

**Comment by ajgilbert** [comment]
No IntegralOneDim in 5_3_27 root, maybe can switch to https://root.cern.ch/doc/master/TF1_8cxx_source.html#l02241 which should call the same function in 7_6_X root, though not that big of a deal as this only breaks analysis code not ntuple production

**Comment by adewit** [comment]
please test

**Comment by adewit** [comment]
please test

**Comment by adewit** [comment]
please test

**Comment by adewit** [comment]
please test

**Pull request merged**
