### PR TITLE
Changes for spring15 ntuple production

### PR DESCRIPTION
**Pull request by adewit**
- CMSSW configs for CMSSW 74X
- Add weight sign for MC@NLO samples
- Store tau dz between leading charged hadron and PV using pat::PackedCandidate::dz() method
- Start of met producer that can produce uncorrected met from miniAOD. There are other values stored in the slimmedMET collection that we could add, something to do in the future - @pjdunne this is probably of interest to you

### CODE REVIEW

**Comment by adewit** [comment]
please test

**Comment by ajgilbert** [comment]
hi, there's quite a lot here but I'll start with the NLO sign first: the implementation is ok, though I did wonder if it would be easier to store using the existing weights mechanism, via `info_->set_weight(sign)`. This would have the advantage that you wouldn't need to do anything special in the analysis code, the weight would be included whenever you call `info->total_weight()`. 

It's also good that saving it is optional in the producer, though I wouldn't worry about only enabling it for NLO samples, just enable it for everything and if you end up storing just a 1 for every event in a LO sample root will compress this nicely.

**Comment by adewit** [comment]
Ok, I think I agree on the first point, I was thinking about this the wrong way. Will change this.

For the second point, I set it up this way because due to the try - catch construction jobs won't fail if the LHEEventProduct doesn't exist, so I wanted some CMSSW printout if it isn't there, but only if it doesn't exist while it should be there (ie it's an NLO sample), not when we don't need it (for LO samples). It's true that this does require things to be configured properly  when submitting the jobs so is actually less safe. I'll think of a different solution.

**Comment by adewit** [comment]
please test

**Comment by ajgilbert** [comment]
right... i've thought about this some more - I agree that if we expect the LHE info to be there and it isn't we need to know about it. In fact instead of doing it in a try block and catching the exception I'd just do it normally and let it crash the program - this way we can be sure we won't miss any problems. 

So this does mean we do need a sample-specific option in the config, but I think instead of creating a separate cmsRun cfg you could just add another option at the top of the cfg and have this propagated to the EventInfoProducer, e.g.

   cmsRun blah_cfg.py isData=0 release=74X isNLO=1

Then it's just a case of having two MC sample lists in the crab cfg right?

**Comment by adewit** [comment]
please test

**Comment by adewit** [comment]
please test

**Comment by adewit** [comment]
please test

**Pull request merged**
