### PR TITLE
Met filters from trigger results

### PR DESCRIPTION
**Pull request by pjdunne**
Adding the ability to store filters in event info that come in the form of an edm::triggerresult

### CODE REVIEW

**Comment by pjdunne** [comment]
please test

**Comment by ajgilbert** [comment]
also ok once fixed. Generally when you use `throw` it's a good idea to throw a named exception, with a message stating the problem. At least it's worth checking if CMSSW will still report which module the exception was in.

**Comment by pjdunne** [comment]
please test

**Comment by pjdunne** [comment]
@ajgilbert it seems that please test isn't triggering the checks, has the machine they run on gone down?

**Comment by ajgilbert** [comment]
yeah the machine decided to go for a little lie-down, i've restarted it - you'll need to request the test again

**Comment by pjdunne** [comment]
thanks

**Comment by pjdunne** [comment]
please test

**Comment by pjdunne** [comment]
please test

**Comment by pjdunne** [comment]
please test

**Comment by pjdunne** [comment]
please test

**Comment by ajgilbert** [comment]
please test

**Pull request merged**
