### PR TITLE
Migration of H->hh code into HiggsTauTau directory

### PR DESCRIPTION
**Pull request by rcl11**
Since the H->hh code is largely the same as the H->tautau code, only small modifications to the H->tautau code were needed. 
Not yet ready for merging - still to be tested to ensure all 3 of the SM, MSSM and H->hh analyses can be produced as before.

### CODE REVIEW

**Comment by rcl11** [comment]
please test

**Comment by ajgilbert** [comment]
please test

**Comment by rcl11** [comment]
@ajgilbert @adewit This has now been tested by myself and Adinda and all seems fine - you can now reproduce the Run 1 H->hh, SM and MSSM results from the one directory (with the exception that it is currently only possible to set either Vegas or Markov-Chain as the choice for SVFit - it is currently set to Markov-Chain). Adinda is currently testing the moving SVFit which can be merged in parallel to this one with one small (easily fixed) merge conflict.

I have not yet merged since it seems like the "please test" tests have failed for 2 of the releases - although the error is the missing SVFit code which should stop all 4 releases compiling, so I am not sure why this has happened for just two. Andrew - if you can confirm that this isn't an issue then feel free to go ahead and merge this. 

Have a good Easter both of you!

**Comment by ajgilbert** [comment]
Hi,

The problem is the other PR with the svfit migration has not been merged yet, and for the two tests that failed there is no CMSSW branch that provides this in the old way.

So the way to proceed is merge the other PR first, then check this one again, at which point we should be good to merge.

For the svfit output files with the Markov chain it would be good to tar and zip a folder and put it somewhere accessible on afs, so it is easy to reproduce the H->hh result in the future.

Cheers
Andrew

On 1 Apr 2015, at 18:59, Rebecca Lane <notifications@github.com<mailto:notifications@github.com>> wrote:


@ajgilbert<https://github.com/ajgilbert> @adewit<https://github.com/adewit> This has now been tested by myself and Adinda and all seems fine - you can now reproduce the Run 1 H->hh, SM and MSSM results from the one directory (with the exception that it is currently only possible to set either Vegas or Markov-Chain as the choice for SVFit - it is currently set to Markov-Chain). Adinda is currently testing the moving SVFit which can be merged in parallel to this one with one small (easily fixed) merge conflict.

I have not yet merged since it seems like the "please test" tests have failed for 2 of the releases - although the error is the missing SVFit code which should stop all 4 releases compiling, so I am not sure why this has happened for just two. Andrew - if you can confirm that this isn't an issue then feel free to go ahead and merge this.

Have a good Easter both of you!

**Comment by adewit** [comment]
please test

**Comment by adewit** [comment]
please test

**Pull request merged**
