### PR TITLE
Adding complex filter module

### PR DESCRIPTION
**Pull request by pjdunne**
Adding a module which can filter an object collection using information held in a different object, e.g. the event info.

It takes two function predicates one which returns a bool and has two parameters of types A and B and another predicate which returns type B and has one parameter of type C.

The use case implemented in HiggsNuNu is getting the jet_rho (which is a double) from the EventInfo, and using it as an input to the PhotonID functions.

### CODE REVIEW

**Comment by pjdunne** [comment]
please test

**Comment by pjdunne** [comment]
please test

**Comment by ajgilbert** [comment]
I was thinking more a Module that can be constructed like this:

~~~cpp
GenericModule("GenericModule")
    .set_event_function([](ic::TreeEvent *evt) {
        auto & x = evt->GetPtrVec("blah");
        auto & y = evt->GetPtr("blah2");
        ic::erase_if(x, [](XType *z) { return SomeFunc(z, y); });
        return 0;
    });
~~~
It would be a way of quickly creating a completely generic module that does not require any persistent state, i.e. not needed class members, and so not needed a full class to implement.

**Comment by pjdunne** [comment]
So the reason I didn't do that was that I couldn't see how to pass erase_if a function with more than one parameter, or how to easily modify it to do so. Is there a simple way?

**Comment by ajgilbert** [comment]
well as in the example above can just use a small lambda function, or use bind like we used to, to fill in the other parameters.

So in general:

```cpp
bool SomeFunction(X x, Y y);

vector<X> xvec;
Y y;
erase_if(xvec, [&](X &x){ return SomeFunction(x, y); });
~~~

**Comment by pjdunne** [comment]
As discussed on skype, I think I'll stick with what I've got for the moment as it works and I need to get a production sent, but look at improving it for the future.

**Pull request merged**
