### PR TITLE
Analysis code and plotting updates

### PR DESCRIPTION
**Pull request by adewit**
This one has become *slightly* too large - sorry! 13 out of these 31 changed files are actually just config file/filelist/submission script/hadding script changes. To the code changes:
- Bugfix in HTT.cpp - it now correctly handles split filelists
- Added a module that just reads the MC weight sign (for calculating nr of effective events in aMC@NLO samples
- Some more updates to output tree variables in HTTCategories
- New DY sample splitting logic. This is still a hybrid version (next update when next round of ntuples with larger genParticles collection comes through)
- Made single lepton and cross triggers for etau and mutau optional (configurable from the config file)
- Some changes to what's printed by HTTPrint 
- Updated samples/backgrounds/methods for plotting (of course just a work in progress atm)

### CODE REVIEW

**Comment by adewit** [comment]
please test

**Comment by ajgilbert** [comment]
more fun today... this is causing problems for the testing machine: https://cern.service-now.com/service-portal/view-outage.do?from=CSP-Service-Status-Board&&n=OTG0023301
i've shut it down for now as it just keeps trying to read from afs in a loop. will try to start it again in an hour or so

**Comment by rcl11** [comment]
Ok yeah this is unfortunately very long, but I was running this last week up to the last 3 commits (which look ok), so I have basically tested all of this pull request. So ok to merge for me.

**Comment by adewit** [comment]
please test

**Comment by pjdunne** [comment]
Fine by me too

**Pull request merged**
